In [5]:
file1=r"C:\Users\swadhin biswal\Desktop\happy data scientist\python\PROJECTS\project1\Consumer_Complaints_train.csv"
file2=r"C:\Users\swadhin biswal\Desktop\happy data scientist\python\PROJECTS\project1\Consumer_Complaints_test_share.csv"

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost.sklearn import XGBClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

In [6]:
ld_train=pd.read_csv(file1)
ld_test=pd.read_csv(file2)

In [14]:
ld_train.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Consumer consent provided?',
       'Submitted via', 'Date sent to company', 'Company response to consumer',
       'Timely response?', 'Consumer disputed?', 'Complaint ID', 'data'],
      dtype='object')

In [10]:
ld_test["Consumer disputed?"]=np.nan

In [13]:
ld_test.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Consumer consent provided?',
       'Submitted via', 'Date sent to company', 'Company response to consumer',
       'Timely response?', 'Consumer disputed?', 'Complaint ID', 'data'],
      dtype='object')

In [12]:
ld_test["data"]="test"
ld_train["data"]="train"
ld_test=ld_test[ld_train.columns]

In [15]:
ld=pd.concat([ld_train,ld_test],axis=0)

In [18]:
ld["Complaint ID"].nunique()

598027

In [19]:
ld["ZIP code"].nunique()

27342

In [21]:
ld.drop(["Complaint ID","ZIP code"],axis=1,inplace=True)

In [22]:
ld.shape

(598027, 17)

In [23]:
ld.dtypes

Date received                   object
Product                         object
Sub-product                     object
Issue                           object
Sub-issue                       object
Consumer complaint narrative    object
Company public response         object
Company                         object
State                           object
Tags                            object
Consumer consent provided?      object
Submitted via                   object
Date sent to company            object
Company response to consumer    object
Timely response?                object
Consumer disputed?              object
data                            object
dtype: object

In [24]:
ld.head()

  Date received                  Product  ...   Consumer disputed?   data
0    2014-05-15              Credit card  ...                   No  train
1    2014-09-18  Bank account or service  ...                   No  train
2    2014-03-13         Credit reporting  ...                   No  train
3    2015-07-17              Credit card  ...                   No  train
4    2014-11-20              Credit card  ...                   No  train

[5 rows x 17 columns]

In [26]:
for col in ld.columns:
    print(col,ld[col].nunique())

Date received 1759
Product 12
Sub-product 47
Issue 95
Sub-issue 68
Consumer complaint narrative 92118
Company public response 10
Company 3437
State 62
Tags 3
Consumer consent provided? 4
Submitted via 6
Date sent to company 1708
Company response to consumer 7
Timely response? 2
Consumer disputed? 2
data 2

In [27]:
for col in ['Date received','Date sent to company']:
    ld[col]=pd.to_datetime(ld[col],infer_datetime_format=True)

In [28]:
ld.head()

  Date received                  Product  ...   Consumer disputed?   data
0    2014-05-15              Credit card  ...                   No  train
1    2014-09-18  Bank account or service  ...                   No  train
2    2014-03-13         Credit reporting  ...                   No  train
3    2015-07-17              Credit card  ...                   No  train
4    2014-11-20              Credit card  ...                   No  train

[5 rows x 17 columns]

In [30]:
ld['day_diff']=pd.to_numeric(ld['Date sent to company']-ld['Date received'])

In [31]:
ld.head()

  Date received        ...                 day_diff
0    2014-05-15        ...           86400000000000
1    2014-09-18        ...          518400000000000
2    2014-03-13        ...         1814400000000000
3    2015-07-17        ...                        0
4    2014-11-20        ...          691200000000000

[5 rows x 18 columns]

In [32]:
ld.drop(["Date sent to company","Date received"],inplace=True,axis=1)

In [33]:
ld.columns

Index(['Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'Tags', 'Consumer consent provided?', 'Submitted via',
       'Company response to consumer', 'Timely response?',
       'Consumer disputed?', 'data', 'day_diff'],
      dtype='object')

In [34]:
ld.isnull().sum()

Product                              0
Sub-product                     173225
Issue                                0
Sub-issue                       365685
Consumer complaint narrative    504376
Company public response         484859
Company                              0
State                             4764
Tags                            513950
Consumer consent provided?      428676
Submitted via                        1
Company response to consumer         0
Timely response?                     0
Consumer disputed?              119606
data                                 0
day_diff                             0
dtype: int64

In [35]:
ld.shape

(598027, 16)

In [39]:
ld.nunique()

Product                            12
Sub-product                        47
Issue                              95
Sub-issue                          68
Consumer complaint narrative    92118
Company public response            10
Company                          3437
State                              62
Tags                                3
Consumer consent provided?          4
Submitted via                       6
Company response to consumer        7
Timely response?                    2
Consumer disputed?                  2
data                                2
day_diff                          420
dtype: int64

In [40]:
for col in ['Sub-product','Sub-issue','Consumer complaint narrative',
            'Company public response','Tags','Consumer consent provided?']:
    varname=col.replace('-','_').replace('?','').replace(" ",'_')+'_isNan'
    ld[varname]=np.where(pd.isnull(ld[col]),1,0)
    ld.drop([col],1,inplace=True)

In [41]:
ld.head()

                   Product               ...               Consumer_consent_provided_isNan
0              Credit card               ...                                             1
1  Bank account or service               ...                                             1
2         Credit reporting               ...                                             1
3              Credit card               ...                                             0
4              Credit card               ...                                             1

[5 rows x 16 columns]

In [42]:
ld_test.isnull().sum()

Date received                        0
Product                              0
Sub-product                      34752
Issue                                0
Sub-issue                        73060
Consumer complaint narrative    101049
Company public response          96830
Company                              0
State                              925
ZIP code                           926
Tags                            102735
Consumer consent provided?       85742
Submitted via                        1
Date sent to company                 0
Company response to consumer         0
Timely response?                     0
Consumer disputed?              119606
Complaint ID                         0
data                                 0
dtype: int64

In [44]:
ld.drop(['Company'],inplace=True,axis=1)

In [45]:
ld.head()

                   Product               ...               Consumer_consent_provided_isNan
0              Credit card               ...                                             1
1  Bank account or service               ...                                             1
2         Credit reporting               ...                                             1
3              Credit card               ...                                             0
4              Credit card               ...                                             1

[5 rows x 15 columns]

In [53]:
k=ld['Issue'].value_counts()
for val in k.index[0:10]:
    varname='Issue_'+val.replace(',','_').replace(' ','_')
    ld[varname]=np.where(ld['Issue']==val,1,0)
del ld['Issue']

In [54]:
ld.head()

                   Product          ...           Issue_Billing_disputes
0              Credit card          ...                                0
1  Bank account or service          ...                                0
2         Credit reporting          ...                                0
3              Credit card          ...                                0
4              Credit card          ...                                0

[5 rows x 24 columns]

In [55]:
k=ld['State'].value_counts()
for val in k.index[0:15]:
    varname='State_'+val.replace(',','_').replace(' ','_')
    ld[varname]=np.where(ld['State']==val,1,0)
del ld['State']

In [56]:
for col in ['Product','Submitted via','Company response to consumer','Timely response?']:
    
    temp=pd.get_dummies(ld[col],prefix=col,drop_first=True)
    ld=pd.concat([temp,ld],1)
    ld.drop([col],1,inplace=True)

In [57]:
ld.head()

   Timely response?_Yes    ...     State_WA
0                     1    ...            0
1                     1    ...            0
2                     1    ...            0
3                     1    ...            0
4                     1    ...            0

[5 rows x 57 columns]

In [58]:
train=ld.loc[ld["data"]=="train",]
test=ld.loc[ld["data"]=="test",]
test.drop(["data","Consumer disputed?"],axis=1,inplace=True)

C:\Users\swadhin\Anaconda3\lib\site-packages\pandas\core\frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

NameError: name 'true' is not defined

In [59]:
train.drop(["data"],axis=1,inplace=True)
train["Consumer disputed?"]=np.where(train["Consumer disputed?"]=="Yes",1,0)

C:\Users\swadhin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [62]:
train["Consumer disputed?"].value_counts()

0    376990
1    101431
Name: Consumer disputed?, dtype: int64

In [64]:
train.shape

(478421, 56)

In [65]:
test.shape

(119606, 55)

In [66]:
ld_train.shape

(478421, 19)